#!/bin/bash

if [[ "$#" -ne '1' ]]; then
    echo "Usage: $(basename $0) \"app name\"" >&2
    exit 1
fi

IFS=$'\n'

appName="$(tr '[:upper:]' '[:lower:]' <<< $1)"
processList=($(
    ps -e | \
    sed -n 's/.*\/\([^/]*\.[a]pp\)\/.*/\1/p' | \
    tr '[:upper:]' '[:lower:]'
))

for ((i=0; i<${#processList[@]}; i++)); do
    if [[ "${processList[$i]}" == "${appName}.app" ]]; then
      kill -9 $(ps -e | grep -i "[${appName:0:1}]${appName##?}.app" | awk '{print $1}')
      exit $?
    fi
done

echo "$1 is not currently running"
