#!/bin/bash

[[ $# -lt 1 || $# -gt 1 ]] && { echo "usage: $(basename $0) \"app name\"" >&2 ; exit 1; }

IFS=$'\n'
appName="$(echo ${1} | tr "[:upper:]" "[:lower:]")"
processList=($(ps -e | sed -n 's/.*\/\([^/]*\.[a]pp\)\/.*/\1/p' | tr "[:upper:]" "[:lower:]"))

for ((i=0;i<${#processList[@]};i++)); do
  [[ "${processList[$i]}" == "${appName}.app" ]] && { kill -9 $(ps -e | grep -i "[${appName:0:1}]${appName##?}.app" | awk '{print $1}'); exit $?; }
done
  echo "${1} is not currently running"
